##
# This file is generated in order to keep in sync with VMs added to vCenter. Don't edit 
# this file directly! Instead, update the template.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 
fe80::1%lo0	localhost

##
# Everything below this is generated by hostfilebot.py (check your cronjobs)
##

